"""rename profile json fields to match schema

Revision ID: 21ec1a7792ec
Revises: 77b9102d722d
Create Date: 2026-09-01 00:18:05.724556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21ec1a7792ec'
down_revision: Union[str, Sequence[str], None] = '77b9102d722d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_experiences_id'), table_name='work_experiences')
    op.drop_table('work_experiences')
    op.drop_index(op.f('ix_language_details_id'), table_name='language_details')
    op.drop_table('language_details')
    op.drop_column('experiences', 'city')
    op.drop_column('experiences', 'country_of_residence')
    op.drop_column('experiences', 'id_number')
    op.drop_column('experiences', 'passport_number')
    op.drop_column('experiences', 'expected_graduation_year')
    op.drop_column('experiences', 'funding_type')
    op.drop_column('experiences', 'field_of_study')
    op.drop_column('experiences', 'phone_number')
    op.drop_column('experiences', 'birth_date')
    op.drop_column('experiences', 'last_name')
    op.drop_column('experiences', 'institution')
    op.drop_column('experiences', 'nationality')
    op.drop_column('experiences', 'gpa_scale')
    op.drop_column('experiences', 'is_completed')
    op.drop_column('experiences', 'financial_status')
    op.drop_column('experiences', 'preferred_fields_of_study')
    op.drop_column('experiences', 'desired_degree_level')
    op.drop_column('experiences', 'preferred_countries')
    op.drop_column('experiences', 'current_study_language')
    op.drop_column('experiences', 'skills_data')
    op.drop_column('experiences', 'documents_data')
    op.drop_column('experiences', 'languages_data')
    op.drop_column('experiences', 'gpa_value')
    op.drop_column('experiences', 'gender')
    op.drop_column('experiences', 'first_name')
    op.drop_column('experiences', 'academic_level')
    op.add_column('profiles', sa.Column('passport_number', sa.String(length=20), nullable=True))
    op.add_column('profiles', sa.Column('documents', sa.JSON(), nullable=True))
    op.add_column('profiles', sa.Column('profile_completion_percentage', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('profiles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('profiles', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('profiles', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('profiles', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('profiles', 'gender',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('MALE', 'FEMALE', name='gender'),
               nullable=False)
    op.alter_column('profiles', 'nationality',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'country_of_residence',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'academic_level',
               existing_type=postgresql.ENUM('BACHELOR', 'MASTER', 'PHD', name='academiclevel'),
               nullable=False)
    op.alter_column('profiles', 'field_of_study',
               existing_type=postgresql.ENUM('ENGINEERING', 'COMPUTER_SCIENCE', 'MEDICINE', 'BUSINESS', 'ARTS', 'OTHER', name='fieldofstudy'),
               nullable=False)
    op.alter_column('profiles', 'institution',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('profiles', 'gpa_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('profiles', 'gpa_scale',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('SCALE_4', 'SCALE_5', 'SCALE_10', 'SCALE_100', name='gpascale'),
               nullable=False)
    op.alter_column('profiles', 'current_study_language',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=False)
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('profiles', 'gpa')
    op.drop_column('profiles', 'father_income')
    op.drop_column('profiles', 'country')
    op.drop_column('profiles', 'degree')
    op.drop_column('profiles', 'marital_status')
    op.drop_column('profiles', 'date_of_birth')
    op.drop_column('profiles', 'country_of_birth')
    op.drop_column('profiles', 'mother_name')
    op.drop_column('profiles', 'full_name')
    op.drop_column('profiles', 'graduation_year')
    op.drop_column('profiles', 'major')
    op.drop_column('profiles', 'id_type')
    op.drop_column('profiles', 'institution_name')
    op.drop_column('profiles', 'address')
    op.drop_column('profiles', 'father_name')
    op.drop_column('profiles', 'documents_data')
    op.drop_column('profiles', 'num_of_siblings')
    op.drop_column('profiles', 'currency')
    op.drop_column('profiles', 'passport_status')
    op.drop_column('profiles', 'mother_income')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('profiles', sa.Column('mother_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('passport_status', postgresql.ENUM('AVAILABLE', 'IN_PROGRESS', 'NOT_AVAILABLE', name='passportavailability'), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('num_of_siblings', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('documents_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('father_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('institution_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('id_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('major', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('graduation_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('mother_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('country_of_birth', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('marital_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('degree', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('father_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('gpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.alter_column('profiles', 'current_study_language',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('profiles', 'gpa_scale',
               existing_type=sa.Enum('SCALE_4', 'SCALE_5', 'SCALE_10', 'SCALE_100', name='gpascale'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'gpa_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('profiles', 'institution',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('profiles', 'field_of_study',
               existing_type=postgresql.ENUM('ENGINEERING', 'COMPUTER_SCIENCE', 'MEDICINE', 'BUSINESS', 'ARTS', 'OTHER', name='fieldofstudy'),
               nullable=True)
    op.alter_column('profiles', 'academic_level',
               existing_type=postgresql.ENUM('BACHELOR', 'MASTER', 'PHD', name='academiclevel'),
               nullable=True)
    op.alter_column('profiles', 'country_of_residence',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'nationality',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'gender',
               existing_type=sa.Enum('MALE', 'FEMALE', name='gender'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('profiles', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('profiles', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('profiles', 'updated_at')
    op.drop_column('profiles', 'created_at')
    op.drop_column('profiles', 'profile_completion_percentage')
    op.drop_column('profiles', 'documents')
    op.drop_column('profiles', 'passport_number')
    op.add_column('experiences', sa.Column('academic_level', postgresql.ENUM('BACHELOR', 'MASTER', 'PHD', name='academiclevel'), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', name='gender'), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('gpa_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('languages_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('documents_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('skills_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('current_study_language', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('preferred_countries', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('desired_degree_level', postgresql.ENUM('BACHELOR', 'MASTER', 'PHD', 'DIPLOMA', 'OTHER', name='desireddegreelevel'), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('preferred_fields_of_study', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('financial_status', postgresql.ENUM('LIMITED', 'MODERATE', 'STABLE', name='financialstatus'), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('gpa_scale', postgresql.ENUM('SCALE_4', 'SCALE_5', 'SCALE_10', 'SCALE_100', name='gpascale'), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('nationality', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('institution', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('phone_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('field_of_study', postgresql.ENUM('ENGINEERING', 'COMPUTER_SCIENCE', 'MEDICINE', 'BUSINESS', 'ARTS', 'OTHER', name='fieldofstudy'), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('funding_type', postgresql.ENUM('FULL', 'PARTIAL', 'SELF', 'ANY', name='fundingtype'), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('expected_graduation_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('passport_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('experiences', sa.Column('id_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('experiences', sa.Column('country_of_residence', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_table('language_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('proficiency_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('certificate_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('language_details_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('language_details_pkey'))
    )
    op.create_index(op.f('ix_language_details_id'), 'language_details', ['id'], unique=False)
    op.create_table('work_experiences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('employment_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_current', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('work_experiences_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('work_experiences_pkey'))
    )
    op.create_index(op.f('ix_work_experiences_id'), 'work_experiences', ['id'], unique=False)
    # ### end Alembic commands ###
